# Ignore false positive from Rails' ActionText and ActiveStorage
CreditCard:
  enabled: false
Delivery:
  enabled: false
Coupon:
  enabled: false
AdminUser:
  password:
    ColumnPresenceChecker:
      enabled: false
Review:
  title:
    NullConstraintChecker:
      enabled: false
  text:
    NullConstraintChecker:
      enabled: false
  rating:
    NullConstraintChecker:
      enabled: false
ActionText::RichText:
  enabled: false
ActiveStorage::Attachment:
  enabled: false
ActiveStorage::Blob:
  enabled: false
ActiveStorage::VariantRecord:
  enabled: false
User:
  enabled: false
Address:
  enabled: false
