# Ignore false positive from Rails' ActionText and ActiveStorage
AdminUser:
  password:
    ColumnPresenceChecker:
      enabled: false
ActionText::RichText:
  enabled: false
ActiveStorage::Attachment:
  enabled: false
ActiveStorage::Blob:
  enabled: false
ActiveStorage::VariantRecord:
  enabled: false
User:
  enabled: false
Address:
  enabled: false
